"""remove peer_review_id from anonymous_reviews

Revision ID: 4b3aecedf706
Revises: 72689f099b42
Create Date: 2025-09-27 20:09:20.307892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3aecedf706'
down_revision = '72689f099b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('self_assessments', schema=None) as batch_op:
        batch_op.alter_column('summary',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('challenges',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('different',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('self_assessments', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('different',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('challenges',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('summary',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
