""" Manual rename columns

Revision ID: 7ecc1082e367
Revises: 48b3c9003228
Create Date: 2025-09-22 21:14:07.698177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ecc1082e367'
down_revision = '48b3c9003228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_number', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('group_members_student_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['id_number'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('student_id')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecturer_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('subjects_teacher_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['lecturer_id'], ['id'])
        batch_op.drop_column('teacher_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_number', sa.String(length=64), nullable=True))
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.drop_column('id_number')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('subjects_teacher_id_fkey'), 'users', ['teacher_id'], ['id'])
        batch_op.drop_column('lecturer_id')

    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('group_members_student_id_fkey'), 'users', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id_number')

    # ### end Alembic commands ###
